[package]
name = "rusty-acse"
version = "0.1.0"
edition = "2024"

[dependencies]
rusty-copp = { path = "../rusty-copp" }
rusty-cosp = { path = "../rusty-cosp" }
rusty-cotp = { path = "../rusty-cotp" }
rusty-tpkt = { path = "../rusty-tpkt" }

rand = "0.9.2"
tracing = "0.1.41"
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["full"] }
der-parser = { version = "10.0.0", features = ["bigint", "serialize"] }

[dev-dependencies]
anyhow = "1.0.98"
tracing-test = "0.2.5"
