[package]
name = "rusty-tpkt"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Implements the TPKT standard to encapsulate ISO protocols for TCP transport."
homepage = "https://github.com/gazzasaur/rusty-iccp"
repository = "https://github.com/gazzasaur/rusty-iccp"

[dependencies]
bytes = "1.10.1"
tracing = "0.1.41"
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["full"] }

[dev-dependencies]
rand = "0.9.2"
anyhow = "1.0.98"
tracing-test = "0.2.5"
